name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install bats
      run: sudo apt-get install bats -y
    - name: Prepare v3.14
      run: ./prepare-branch.sh prepare v3.14
      working-directory: docker-alpine
    - name: Build Container
      run: sh -c "cd /tmp/docker-brew-alpine-*/x86_64 && docker build --tag ghcr.io/jgowdy/alpine:latest --tag ghcr.io/jgowdy/alpine:3.14 . "
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/alpine:latest
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/alpine:3.14
