name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install bats
      run: sudo apt-get install bats -y
    - name: Prepare v3.14
      run: ./prepare-branch.sh prepare v3.14
      working-directory: docker-alpine

